// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEvmHBFLk1NCb8O4_BowIQeoVtI3AmCuQ',
    appId: '1:1095491118733:web:e6e32b29b6915dd866a4c4',
    messagingSenderId: '1095491118733',
    projectId: 'finaltsa',
    authDomain: 'finaltsa.firebaseapp.com',
    storageBucket: 'finaltsa.appspot.com',
    measurementId: 'G-EWSQGGX4HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3DZCkaVM7d5w2bZR9TwNyczx9vvn0GWw',
    appId: '1:1095491118733:android:d110a1d45ea9273566a4c4',
    messagingSenderId: '1095491118733',
    projectId: 'finaltsa',
    storageBucket: 'finaltsa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqDSK3v3EIxqCzSx2nyclKJcu5iPXR6s',
    appId: '1:1095491118733:ios:0b20e05513771c1566a4c4',
    messagingSenderId: '1095491118733',
    projectId: 'finaltsa',
    storageBucket: 'finaltsa.appspot.com',
    iosClientId: '1095491118733-nf8j4u7iiqt5fbtnb1dudkame9k81h6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.slide1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVqDSK3v3EIxqCzSx2nyclKJcu5iPXR6s',
    appId: '1:1095491118733:ios:0b20e05513771c1566a4c4',
    messagingSenderId: '1095491118733',
    projectId: 'finaltsa',
    storageBucket: 'finaltsa.appspot.com',
    iosClientId: '1095491118733-nf8j4u7iiqt5fbtnb1dudkame9k81h6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.slide1',
  );
}
